---
#
# edX Configuration
#
# github:     http://gitlab.cse.iitb.ac.in/indiax/configuration
# wiki:       http://gitlab.cse.iitb.ac.in/indiax/configuration/wiki
# code style: http://gitlab.cse.iitb.ac.in/indiax/configuration/wiki/Ansible-Coding-Conventions
# license:    http://gitlab.cse.iitb.ac.in/indiax/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role stop_all_edx_services
#

#
# vars are namespace with the module name.
#
stop_all_edx_services_role_name: stop_all_edx_services
