---
#
# edX Configuration
#
# github:     http://gitlab.cse.iitb.ac.in/indiax/configuration
# wiki:       http://gitlab.cse.iitb.ac.in/indiax/configuration/wiki
# code style: http://gitlab.cse.iitb.ac.in/indiax/configuration/wiki/Ansible-Coding-Conventions
# license:    http://gitlab.cse.iitb.ac.in/indiax/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role alton
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: create application user
  user: >
    name="{{ alton_user }}" home="{{ alton_app_dir }}"
    createhome=no shell=/bin/false

- name: create alton user dirs
  file: >
    path="{{ item }}" state=directory
    owner="{{ alton_user }}" group="{{ common_web_group }}"
  with_items:
    - "{{ alton_app_dir }}"
    - "{{ alton_venvs_dir }}"

- name: setup the alton env
  template: >
    src="alton_env.j2" dest="{{ alton_app_dir }}/alton_env"
    owner="{{ alton_user }}" group="{{ common_web_user }}"
    mode=0644
  notify: restart alton

- include: deploy.yml tags=deploy
