#
# edX Configuration
#
# github:     http://gitlab.cse.iitb.ac.in/indiax/configuration
# wiki:       http://gitlab.cse.iitb.ac.in/indiax/configuration/wiki
# code style: http://gitlab.cse.iitb.ac.in/indiax/configuration/wiki/Ansible-Coding-Conventions
# license:    http://gitlab.cse.iitb.ac.in/indiax/configuration/blob/master/LICENSE.TXT
#
#
#
# Defaults for role gh_mirror
#
---
gh_mirror_nginx_port: 80
gh_mirror_server_name: 'git.*'
gh_mirror_data_dir: /var/git/mirrors
gh_mirror_app_dir: /opt/gh_mirror
gh_mirror_user: git-mirror
gh_mirror_group: git-mirror
gh_mirror_orgs:
  - edX
  - MITx
  - eventbrite
  - dementrock
  - mfogel
  - mitocw
  - Stanford-Online
gh_mirror_debian_pkgs:
  - fcgiwrap
gh_mirror_pip_pkgs:
  - pyyaml
  - requests
gh_mirror_app_files:
  - repos_from_orgs.py
