---
- name: Install nginx packages
  apt: pkg={{','.join(nginx_debian_pkgs)}} state=present
  notify: restart nginx

- name: Server configuration file
  template: >
    src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    owner=root group=www-data mode=0644
  notify: reload nginx

- name: make sure nginx has started
  service: name=nginx state=started
