---
#
# edX Configuration
#
# github:     http://gitlab.cse.iitb.ac.in/indiax/configuration
# wiki:       http://gitlab.cse.iitb.ac.in/indiax/configuration/wiki
# code style: http://gitlab.cse.iitb.ac.in/indiax/configuration/wiki/Ansible-Coding-Conventions
# license:    http://gitlab.cse.iitb.ac.in/indiax/configuration/blob/master/LICENSE.TXT
#
#
#
# Handlers for role haproxy
# 
# Overview:
# 
#
- name: restart haproxy
  service: name=haproxy state=restarted

- name: reload haproxy
  service: name=haproxy state=reloaded

- name: restart rsyslog
  service: name=rsyslog state=restarted
